import { Activity } from './activity.type';

export const ACTIVITIES: Activity[] = [
  {
    id: 1,
    name: 'Standup Surfing',
    slug: 'standup-surfing_laco-di-como_2023-08-01',
    price: 30,
    duration: 120,
    location: 'Laco di Como',
    date: '2023-08-01',
    maxParticipants: 10,
    minParticipants: 2,
    status: 'done',
    userId: 1,
  },
  {
    id: 2,
    name: 'Kayaking',
    slug: 'kayaking_grand-canyon_2023-07-14',
    price: 50,
    duration: 180,
    location: 'Grand Canyon',
    date: '2023-07-14',
    maxParticipants: 12,
    minParticipants: 6,
    status: 'cancelled',
    userId: 1,
  },
  {
    id: 3,
    name: 'Surfing',
    slug: 'surfing_hawaii_2023-03-08',
    price: 40,
    duration: 90,
    location: 'Hawaii',
    date: '2023-03-08',
    maxParticipants: 8,
    minParticipants: 4,
    status: 'done',
    userId: 2,
  },
  {
    id: 4,
    name: 'Sailing',
    slug: 'sailing_mediteranean-sea_2024-09-28',
    price: 160,
    duration: 120,
    location: 'Mediteranean Sea',
    date: '2024-09-28',
    maxParticipants: 8,
    minParticipants: 4,
    status: 'published',
    userId: 1,
  },
  {
    id: 5,
    name: 'Hiking',
    slug: 'hiking_alps_2024-07-28',
    price: 20,
    duration: 240,
    location: 'Alps',
    date: '2024-07-28',
    maxParticipants: 20,
    minParticipants: 10,
    status: 'published',
    userId: 2,
  },
];
